dist: trusty
sudo: required
language:
  - python
python:
  - "3.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
  # Installing Python dependencies
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cd test/
  - py.test *