language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - sudo apt install g++ -y
  - g++ -v
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - cd test/
  - py.test *